from nova_prompt import return_nova_prompt
from custom_openai_chat_call import custom_openai_chat_call

# Automatically run the Nova prompt and save the output to a markdown file
def run_nova_prompt():
    print("Running Nova Prompt...")
    n_p = return_nova_prompt()
    custom_openai_chat_call({"role": "system", "content": n_p})
    # print(n_p)
    # Prime the bot for it's first use of Nova by using the n_p prompt as the system message
    # Every time the bot is used after this, it will use the continuation prompt, which is generated by another call to OpenAI, but with that specific bot's system message priming it
    # Example:
    # Bot1 uses n_p to receive input from the user
    # Bot2 is fed Bot1's output as its input, and uses the continuation prompt and its system message to generate its output


def run ():
    run_nova_prompt()

if __name__ == "__main__":
    run()